config/routes.rb
Rails.application.routes.draw do
  resources :friendships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create]

  get '/inbox' => 'messages#inbox'
  delete '/logout' => 'sessions#destroy'
  get 'sent_messages' => 'messages#sent_messages'
  root 'users#welcome'

  resources :messages do
  end

  resources :users do
    resources :messages
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user #belongs to user which is going to be who is goign to be initiator or owner of this friendship
  belongs_to :friend, :class_name => 'User' #belongs toa friend which is another user, because we can't determined by the name friend we need to specify the class name in here and say we want to use user has model fot this association
end

app/models/message.rb
class Message < ApplicationRecord

  validates :sender_id, presence: true
  validates :recipient_id, presence: true
  validates_presence_of :body, :recipient_id
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'


  #Scoping allows you to specify commonly-used queries which can be referenced as method calls on the association objects
  # or models
  # scope :unread, -> { where(read_at: nil) }

  # the '!' indicates at the end is a convention to hint that we are making changes to the message
  # the '!' indicates sometimes alos means that it may raise an error if the condition is not satisfied
  # int this case : we use  both meanings, because we also call save! inside, which means it will raise error if cannot save
  # def mark_as_read!
  #   self.read_at = Time.now
  #   save!
  # end
  #
  # #convenience
  # def read?
  #   read_at
  # end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_insenssiitve: false}
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  has_secure_password

  #adding an Association anf the way we do that here is  Many to Many
  #this is to add the friends and (whom you want to add)
  has_many :friendships
  has_many :friends, :through => :friendships
  # this is for ==> who all Added you as a friend opposite side (opponent side)
  has_many :inverse_friendships, :class_name => 'Friendship', :foreign_key => 'friend_id'
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  #incoming messages == received_messages
  def received_messages
    #User.where(recipient: self)
    Message.where(recipient_id: id)
  end

  #outgoing messages == sent_messages
  def sent_messages
    # User.where(sender: self)
    Message.where(sender_id: id)
  end

  # and we can "chain" methods to load n newest received messages
  def latest_received_messages(n)
    received_messages.order(created_at: :desc).limit(n)
  end


  def latest_send_messages(n)
    sent_messages.order(read_at: :desc).limit(n)
  end

  def unread_messages
    received_messages.unread
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return @current_user if @current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    if @friendship.save
      flash[:success] = 'You have Added friend to your list.'
      redirect_to users_path
    else
      flash[:info] = 'Unable to Add friend.'
      redirect_to users_path
    end
  end


  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:info] = 'You have removed a friend from your list successfully'
    redirect_to current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  after_filter :message_read, only: :show
  # before_filter :check_recipient

  def check_recipient

    if session[:user_id] != current_user
      redirect_to root_path
    end
  end

  def index
    @messages = Message.all
  end

  def inbox
    @received_messages = Message.where(recipient_id: current_user.id).order('created_at DESC').limit(5)
  end

  def sent_messages
    @sent_messages = Message.where(sender_id: current_user.id).order('read_at DESC').limit(5)
  end

  def show
    @message = Message.find params[:id]
    if @message.recipient_id == current_user.id
      if @message.read_at.nil?
        @message.update_columns(read_at: Time.now)
      end
    end
    unless @message.recipient_id == current_user.id
      flash[:error] = 'You are not authorized to view this message !!!'
      redirect_to root_path
    end
  end

  def message_read
    if !@message.read.present? && current_user == @message.recipient
      @message.update_columns(read: true)
    end
  end

  def new
    @user = current_user
    @message = Message.new
  end

  def create
    # @user = User.find params[:user_id]
    @message = Message.new(messages_params)
    @message.sender_id = current_user.id
    # @messages = User.sent_messages.build
    if @message.save
      flash[:success] = 'Message sent successfully'
      redirect_to sent_messages_path
    end
  end

  def sent
    load_user
    @messages = @user.sent_messages
  end

  def received
    load_user
    @messages = @user.received_messages
  end

  def load_user
    if params[:user_id]
      @user = User.find params[:user_id]
    else
      @user = current_user
    end
  end

  private
  def messages_params
    params.require(:message).permit(:body, :recipient_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if @user = User.find_by(email: params[:email])
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = 'welcome back'
        redirect_to user_path(@user.id)
      else
        flash[:error] = 'wrong password'
        redirect_to new_session_path
      end
    else
      flash[:error] = 'Email not Found'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # Rails.logger.info requst.enc["HTTP_COKIE"]
    @users = User.all
  end

  def new
    @user = User.new
  end


  def welcome

  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Thanks you for signing up! you are now logged in.'
      redirect_to users_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= form_for(friendship) do |f| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :friend_id %>
    <%= f.number_field :friend_id %>
  </div>

  <div class="field">
    <%= f.label :create %>
    <%= f.text_field :create %>
  </div>

  <div class="field">
    <%= f.label :destroy %>
    <%= f.text_field :destroy %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/_nav_bar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo" style="margin-left: 2cm;">Lol chat</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
          <li><a href="<%= messages_path %>"><i class="material-icons">home</i></a></li>
          <li class="nav-item">
            Welcome <%= current_user.name %>! Not you? <%= link_to 'Log out', logout_path, method: 'delete' %>
          </li>
          <li class="nav-item">
            <%= link_to 'View Profile', user_path(current_user) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Send Message', new_message_path %>
          </li>
          <li class="nav-item">
            <%= link_to 'Inbox', inbox_path %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Create An account', new_user_path %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_session_path %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lolchat</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/nav_bar' %>
  <%= render partial: 'shared/flash_messages', flash: flash %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_add_friend.html.erb
<h4>To Add New Friends</h4>

app/views/messages/_incoming_messages.html.erb
<h4>we need to render Incoming Message here</h4>

app/views/messages/_message.html.erb
<%= render 'shared/errors', obj: @message %>
<h1 class="text-sm-center">Send Message to your friend</h1>
<div class="container">
  <div class="row col-md-12" style="border:1px solid black; padding: 30px 30px 30px 30px;">
    <%= simple_form_for @message do |f| %>
        <%= f.association :recipient, collection: current_user.friends, :include_blank => false %>
        <%= f.input :body, :placeholder => 'Enter your message...', :class => 'validate' %>
        <%= f.button :submit, 'Send Message', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/messages/_received_messages.html.erb
<hr>
<% @received_messages.each do |received_message| %>
    <% if received_message.read == true %>
        <p>From: <%= received_message.sender.name %></p>
        <p><strong style="color: green;">Status: Read</strong></p>
    <% else %>
        <p>
          From <%= link_to received_message, title: 'Click to see the message' do %>
              <%= received_message.sender.name %>
          <% end %>
        </p>
        <p><strong style="color:red;">Status: Unread</strong></p>
    <% end %>

    <em>Received at: <%= received_message.created_at.strftime("%H:%I %p, %d/%m/%Y") %></em>
    <hr>
<% end %>

app/views/messages/_sent_messages.html.erb
<h4>To Display Sent Messages</h4>

app/views/messages/inbox.html.erb
<h1> Your Inbox</h1>
<div class="collection">
  <% @received_messages.each do |received_message| %>

      <% if received_message.read == true %>
          <div class="collection-item">
            <strong><%= received_message.sender.name %></strong>

            <p><strong style="color: green;">Status: Read</strong></p>
            <em>Received
              at: <%= received_message.created_at.strftime("%H:%I %p, %d/%m/%Y") %></em>
          </div>

      <% else %>
          <div class="collection-item">
            <%= link_to 'Read Your Message Here', received_message  %>
            <p><strong style="color: red;">Status: Unread</strong></p>
            <em>Received
              at: <%= received_message.created_at.strftime("%H:%I %p, %d/%m/%Y") %></em>
          </div>
      <% end %>

  <% end %>
</div>

app/views/messages/index.html.erb
<h1>Message Index page</h1>
<% @messages.each do |message| %>
    <li><%= message.body %></li>
<% end %>
<%= form_for @new_message do |f| %>
    <div class="container">
      <%= f.label :body %>
      <%= f.text_field :body %>
      <%= f.submit 'send' %>
    </div>
<% end %>

app/views/messages/new.html.erb
<%= render 'message' %>

app/views/messages/received.html.erb
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a href="#test1">Incoming Messages</a></li>
      <li class="tab col s3"><a class="active" href="#test2">New Message</a></li>
      <li class="tab col s3"><a class="active" href="#test3">Add Friend</a></li>
      <li class="tab col s3"><a href="#test4">Sent Messages</a></li>
    </ul>
  </div>
  <div id="test1" class="col s12"><%= render 'incoming_messages' %></div>
  <div id="test2" class="col s12"><%= render 'message' %></div>
  <div id="test3" class="col s12"><%= render 'add_friend'%></div>
  <div id="test4" class="col s12"><%= render 'sent_messages' %></div>
</div>

app/views/messages/sent_messages.html.erb
<h4 align="center">Your Sent Messages</h4>
<div class="container">
  <div class="row col-md-12" style="border:1px solid black; padding: 30px 30px 30px 30px;">
    <% @sent_messages.each do |sent_message| %>
        <p><strong>To: <%= sent_message.recipient.name %></strong></p>
        <% if sent_message.read == true %>
            <p><strong style="color: green;">Status: Read</strong></p>
            <em style="color: green;">Read at: <%= sent_message.try(:read_at) %></em>
        <% else %>
            <p><strong style="color: red;">Status: Not read yet!</strong></p>
            <em style="color: red;">Sent at: <%= sent_message.try(:created_at) %></em>
        <% end %>
        <hr>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel teal">
      <% if @message.read == true %>
          <span class="white-text"><h5>you have already read</h5></span>
      <% else %>
          <span class="white-text"><h6><%= @message.body %></h6></span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-header card-inverse card-danger">
            <div class="card-title">
              <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:
            </div>
            <div class="card-text">
              <ul>
                <% obj.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <% if name == "danger" %>
            <div class="alert alert-danger" style="margin-top: 10px"/>
        <% else %>
            <div class="alert alert-success" style="margin-top: 10px"/>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <h1>Users List</h1>
  <table class="table table-striped centered">
    <thead>
    <tr>
      <th data-field="id">Name</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
          <% unless user.name == current_user.name %>
            <td><strong><%= user.name %></strong></td>
            <td><%= link_to 'Add Friend', friendships_path(:friend_id => user), :method => :post %></td>
        <% end %>
          <!--we are trying to navigate to friendships controller create action cal friendships_path with method post, that will trigger a post request to got to create action in our frienships controller-->
          <!--and we need to specify for which user we are trying to add as a friend, we can do that by just passing an additional parameter friend_id as the user that will pass on the user 's ID with their sow e can grab it in our friendships create action-->
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h2 align="center">Create An Account</h2>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4>
            <%= pluralize(@user.errors.count, "error") %>
            Prohibited this User from being created.
          </h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li> <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="container">
      <div class="row col-md-12" style="border:1px solid black; padding: 30px 30px 30px 30px;">

        <div class="input-field ">
          <%= f.label :name %>
          <%= f.text_field :name, :placeholder => 'Enter your name...', :class => "validate" %>
        </div>

        <div class="input-field ">
          <%= f.label :email %>
          <%= f.text_field :email, :placeholder => 'Enter your Email...', class: 'validate' %>
        </div>

        <div class="input-field ">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: 'please enter your password...', class: 'validate' %>
        </div>

        <div class="input-field ">
          <%= f.submit 'Create Account', class: 'btn btn-secondary ' %>
        </div>

      </div>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">My Profile</span>

        <p>Username : <strong><%= @user.name %></strong></p>
      </div>
      <div class="card-action">
        <h5> &#8594; Friends</h5>

        <div class="container">
          <% @user.friendships.each do |friendship| %>
              <li class="white-text"><%= friendship.friend.name %> &nbsp
                &nbsp <%= link_to 'REMOVE', friendship, :method => :delete %></li>
          <% end %>
        </div>
        <br>
        <%= link_to 'Find Friends', users_path, :class => "waves-effect waves-light btn" %>

        <h5> &#8594; Friends by users</h5>

        <div class="container">
          <ul>
            <% @user.inverse_friends.each do |inverse_friends| %>
                <li class="white-text"><%= inverse_friends.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>